apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRE_USERNAME: {{ .Values.secrets.data.db_username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.data.db_password | quote }}